#!/bin/bash

USRdatabase="${ADM_user}/ADMuser"
[[ ! -d ${ADM_user}/B-ADMuser ]] && mkdir ${ADM_user}/B-ADMuser

err_fun(){
  case $1 in
    1)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Null client")"; sleep 2s; tput cuu1; tput dl1;;
    2)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Client name too short")"; sleep 2s; tput cuu1; tput dl1;;
    3)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Client name too long")"; sleep 2s; tput cuu1; tput dl1;;
    4)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Empty password")"; sleep 2s; tput cuu1; tput dl1;;
    5)tput cuu1; tput dl1 && msg -verm "$(fun_trans "TOKEN too short, check character count")"; sleep 2s; tput cuu1; tput dl1;;
    6)tput cuu1; tput dl1 && msg -verm "$(fun_trans "TOKEN too long, check character count")"; sleep 2s; tput cuu1; tput dl1;;
    7)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Empty duration")"; sleep 2s; tput cuu1; tput dl1;;
    8)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Invalid duration, use numbers")"; sleep 2s; tput cuu1; tput dl1;;
    9)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Maximum duration is one year")"; sleep 2s; tput cuu1; tput dl1;;
    11)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Empty limit")"; sleep 2s; tput cuu1; tput dl1;;
    12)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Invalid limit, use numbers")"; sleep 2s; tput cuu1; tput dl1;;
    13)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Maximum limit is 999")"; sleep 2s; tput cuu1; tput dl1;;
    14)tput cuu1; tput dl1 && msg -verm "$(fun_trans "Client or TOKEN already exists")"; sleep 2s; tput cuu1; tput dl1;;
  esac
}

data_user(){
    cat_users=$(cat "/etc/passwd"|grep 'home'|grep 'false'|grep -v 'syslog')
  [[ -z "$(echo "${cat_users}"|awk -F ':' '{print $5}'|cut -d ',' -f1|grep -w 'token'|head -1)" ]] && print_center -verm2 "NO TOKEN CLIENTS REGISTERED" && return 1
    dat_us=$(printf '%-20s%-12s%-8s%s' 'Client' 'Date' 'Days' 'Status')
    msg -azu "  N°  $dat_us"
    msg -bar

    i=1
    for u in `echo "${cat_users}"|awk -F ':' '{print $1}'`; do

    fix_hwid_token=$(echo "${cat_users}"|grep -w "$u"|awk -F ':' '{print $5}'|cut -d ',' -f1) && [[ "${fix_hwid_token}" != @(token) ]] && continue

        fecha=$(chage -l "$u"|sed -n '4p'|awk -F ': ' '{print $2}')

        mes_dia=$(echo $fecha|awk -F ',' '{print $1}'|sed 's/ //g')
        ano=$(echo $fecha|awk -F ', ' '{printf $2}'|cut -c 3-)
        us=$(printf '%-12s' "$u")

        pass=$(cat "/etc/passwd"|grep -w "$u"|awk -F ':' '{print $5}'|cut -d ',' -f2)
        [[ "${#pass}" -gt '12' ]] && pass="Unknown"
        pass="$(printf '%-19s' "$pass")"

        unset stat
        if [[ $(passwd --status $u|cut -d ' ' -f2) = "P" ]]; then
            stat="$(msg -verd "ULK")"
        else
            stat="$(msg -verm2 "LOK")"
        fi

        echo -ne "  $(msg -verd "$i)")$(msg -verm2 "-") $(msg -azu "${pass}")"
        if [[ $(echo $fecha|awk '{print $2}') = "" ]]; then
            exp="$(printf '%8s%-2s' '[X]')"
            exp+="$(printf '%-6s' '[X]')"
            echo " $(msg -verm2 "$fecha")$(msg -verd "$exp")$(echo -e "$stat")"	
        else
            if [[ $(date +%s) -gt $(date '+%s' -d "${fecha}") ]]; then
                exp="$(printf '%-5s' "Exp")"
                echo " $(msg -verm2 "$mes_dia/$ano")  $(msg -verm2 "$exp")$(echo -e "$stat")"
            else
                EXPTIME="$(($(($(date '+%s' -d "${fecha}") - $(date +%s))) / 86400))"
                if [[ "${#EXPTIME}" = "1" ]]; then
            exp="$(printf '%6s%-7s' "$EXPTIME")"
        elif [[ "${#EXPTIME}" = "2" ]]; then
            exp="$(printf '%7s%-6s' "$EXPTIME")"
        else
            exp="$(printf '%7s%-5s' "$EXPTIME")"
        fi
                echo " $(msg -verm2 "$mes_dia/$ano")$(msg -verd "$exp")$(echo -e "$stat")"
            fi
        fi
    echo -e "      $(msg -ama "TOKEN:") $(msg -azu "${us}")"
    msg -bar3
        let i++
    done
  tput cuu1 && tput dl1

}

#======CREATE NEW USER===========
#useradd -M -s /bin/false -e 2021-10-16 -K PASS_MAX_DAYS=1 ruso99
add_user(){
  Fecha=`date +%d-%m-%y-%R`
  [[ $(cat /etc/passwd |grep $1: |grep -vi [a-z]$1 |grep -v [0-9]$1 > /dev/null) ]] && return 1
  valid=$(date '+%C%y-%m-%d' -d " +$3 days")
  clear
  msg -bar

  system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
  distro=$(echo "$system"|awk '{print $1}')
  vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1)

  tpass=$(cat ${ADM_user}/passwd_token)

  if [[ ${distro} = @(Ubuntu|Debian) ]]; then
    if [[ ${vercion} = "16" ]]; then
      pass=$(openssl passwd -1 $tpass)
    else
      pass=$(openssl passwd -6 $tpass)
    fi
  fi

  if useradd -M -s /bin/false -e ${valid} -K PASS_MAX_DAYS=$3 -p ${pass} -c token,$1 $2 ; then

    if [[ $4 = @(s|S) ]]; then
      rm -rf /etc/openvpn/easy-rsa/pki/reqs/$1.req
      rm -rf /etc/openvpn/easy-rsa/pki/issued/$1.crt
      rm -rf /etc/openvpn/easy-rsa/pki/private/$1.key
      cd /etc/openvpn/easy-rsa/
      ./easyrsa build-client-full $1 nopass > /dev/null 2>&1
      cd
      cp /etc/openvpn/client-common.txt ~/$1.ovpn
      echo "<ca>" >> ~/$1.ovpn
      cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$1.ovpn
      echo "</ca>" >> ~/$1.ovpn
      echo "<cert>" >> ~/$1.ovpn
      cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> ~/$1.ovpn
      echo "</cert>" >> ~/$1.ovpn
      echo "<key>" >> ~/$1.ovpn
      cat /etc/openvpn/easy-rsa/pki/private/$1.key >> ~/$1.ovpn
      echo "</key>" >> ~/$1.ovpn
      echo "<tls-auth>" >> ~/$1.ovpn
      cat /etc/openvpn/ta.key >> ~/$1.ovpn
      echo "</tls-auth>" >> ~/$1.ovpn

      cd $HOME
      zip ./$1.zip ./$1.ovpn > /dev/null 2>&1
      rm ./$1.ovpn > /dev/null 2>&1

      zip_ovpn="$HOME/$1.zip"

    fi

      print_center -verd "$(fun_trans "User created successfully")"
  else
      print_center -verm2 "$(fun_trans "Error, User not created")"
      msg -bar
      sleep 3
      return
  fi
  msg -bar
}

mostrar_usuarios(){
  for u in `cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w 'token'|awk -F ':' '{print $1}'`; do
    echo "$u"
  done
}

new_user(){
  fpass="${ADM_user}/passwd_token" && [[ ! -e "${fpass}" ]] && touch ${fpass}
  apass=$(cat ${ADM_user}/passwd_token)
  if [[ -z "$apass" ]]; then
    clear
    msg -bar
    print_center -ama "NO TOKEN PASSWORD CONFIGURED\nCONFIGURE A PASSWORD TO CONTINUE"
    enter
    tpass
  fi
  clear
  usuarios_ativos=('' $(mostrar_usuarios))
  msg -bar
  print_center -ama "$(fun_trans "CREATE USERS")"
  msg -bar
  data_user
  back

  while true; do
    msg -ne "$(fun_trans "Client Name"): "
    read cliente
    cliente="$(echo $cliente|sed 'y/áÁàÀãÃâÂéÉêÊíÍóÓõÕôÔúÚñÑçÇªº/aAaAaAaAeEeEiIoOoOoOuUnNcCao/')"
    cliente="$(echo $cliente|sed -e 's/[^a-z0-9 -]//ig')"
    if [[ -z $cliente ]]; then
      err_fun 1 && continue
    elif [[ "${cliente}" = "0" ]]; then
      return
    elif [[ "${#cliente}" -lt "4" ]]; then
      err_fun 2 && continue
    elif [[ "${#cliente}" -gt "20" ]]; then
      err_fun 3 && continue
    elif [[ "$(echo ${usuarios_ativos[@]}|grep -w "$cliente")" ]]; then
      err_fun 14 && continue
    fi
    break
  done

  while true; do
    msg -ne "$(fun_trans "TOKEN")"
    read -p ": " token
    token="$(echo $token|sed 'y/áÁàÀãÃâÂéÉêÊíÍóÓõÕôÔúÚñÑçÇªº/aAaAaAaAeEeEiIoOoOoOuUnNcCao/')"
    if [[ -z $token ]]; then
      err_fun 4 && continue
    elif [[ "${#token}" -lt "10" ]]; then
      err_fun 5 && continue
    elif [[ "${#token}" -gt "20" ]]; then
      err_fun 6 && continue
    fi
    break
  done

  while true; do
    msg -ne "$(fun_trans "Connection time")"
    read -p ": " diasuser
    if [[ -z "$diasuser" ]]; then
      err_fun 7 && continue
    elif [[ "$diasuser" != +([0-9]) ]]; then
      err_fun 8 && continue
    elif [[ "$diasuser" -gt "360" ]]; then
      err_fun 9 && continue
    fi 
    break
  done

  [[ $(dpkg --get-selections|grep -w "openvpn"|head -1) ]] && [[ -e /etc/openvpn/openvpn-status.log ]] && {

    while [[ ${newfile} != @(s|S|y|Y|n|N) ]]; do
      msg -ne "$(fun_trans "Create OpenVPN File")? [Y/N]: "
      read -e -i S newfile
    done
  }

  add_user "${cliente}" "${token}" "${diasuser}" "${newfile}"

  msg -ne " $(fun_trans "Server IP"): " && msg -ama "    $(fun_ip)"
  msg -ne " $(fun_trans "Client"): " && msg -ama "            $cliente"
  msg -ne " $(fun_trans "Duration days"): " && msg -ama "   $diasuser"
  msg -ne " $(fun_trans "Expiration Date"): " && msg -ama "$(date "+%F" -d " + $diasuser days")"
  [[ ! -z "$zip_ovpn" ]] && msg -ne " $(fun_trans "OVPN file"): " && msg -ama "       $zip_ovpn"
  msg -ne " $(fun_trans "TOKEN"): " && msg -ama "$token"
  msg -bar
  print_center -ama "►► Press enter to continue ◄◄"
  read
  return 1
}
#===================================

#======CREATE TEMPORARY USER======

mktmpuser(){
    while [[ -z $name ]]; do
        msg -ne " Username: "
        read name
        if [[ -z $name ]]; then
            tput cuu1 && tput dl1
            msg -ama " Enter a username"
            sleep 2
            tput cuu1 && tput dl1
            unset name
            continue
        fi
    done

    if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null ; then
        tput cuu1 && tput dl1
        msg -verm2 " The user $name already exists"
        sleep 2
        tput cuu1 && tput dl1
        return
    fi

    while [[ -z $pass ]]; do
        msg -ne " Password: "
        read pass
        if [[ -z $pass ]]; then
            tput cuu1 && tput dl1
            msg -ama " Enter a password"
            sleep 2
            tput cuu1 && tput dl1
            unset pass
            continue
        fi
    done

    while [[ -z $tmp ]]; do
        msg -ne " Duration in minutes: "
        read tmp
        if [[ -z $tmp ]]; then
            tput cuu1 && tput dl1
            msg -ama " Enter a duration time"
            sleep 2
            tput cuu1 && tput dl1
            unset tmp
            continue
        fi
    done

    if [[ -z $1 ]]; then
        msg -ne " Apply to Default conf [Y/N]: "
        read def
        if [[ ! "$def" != @(s|S|y|Y) ]]; then
            echo -e "usuario=$name
Contraseña=$pass
Tiempo=$tmp" > ${Default}
        fi
    fi

    useradd -M -s /bin/false -p $(openssl passwd -6 $pass) $name
    #(echo $pass; echo $pass)|passwd $name 2>/dev/null
    touch /tmp/$name

    timer=$(( $tmp * 60 ))
    timer2="'$timer's"
    echo "#!/bin/bash
sleep $timer2
kill"' $(ps -u '"$name |awk '{print"' $tmp'"}') 1> /dev/null 2> /dev/null
userdel --force $name
rm -rf /tmp/$name
exit" > /tmp/$name

    chmod 777 /tmp/$name
    touch /tmp/cmd
    chmod 777 /tmp/cmd
    echo "nohup /tmp/$name & >/dev/null" > /tmp/cmd
    /tmp/cmd 2>/dev/null 1>/dev/null
    rm -rf /tmp/cmd

    title "TEMPORARY USER CREATED"
    echo -e " $(msg -verm2 "IP:        ") $(msg -ama "$(fun_ip)")"
    echo -e " $(msg -verm2 "User:      ") $(msg -ama "$name")"
    echo -e " $(msg -verm2 "Password:  ") $(msg -ama "$pass")"
    echo -e " $(msg -verm2 "Duration:  ") $(msg -ama "$tmp minutes")"
    msg -bar
    read foo
    return
}

userTMP(){
    tmp_f="${ADM_user}/userTMP" && [[ ! -d ${tmp_f} ]] && mkdir ${tmp_f}
    Default="${tmp_f}/Default"
    if [[ ! -e ${Default} ]]; then
        echo -e "usuario=ADMRufu
Contraseña=ADMRufu
Tiempo=15" > ${Default}
    fi

    name="$(cat ${Default}|grep "usuario"|cut -d "=" -f2)"
    pass="$(cat ${Default}|grep "Contraseña"|cut -d "=" -f2)"
    tmp="$(cat ${Default}|grep "Tiempo"|cut -d "=" -f2)"

    title "TEMPORARY USER CONFIG"
    print_center -teal "Default User"
    msg -bar3
    echo -e " $(msg -verm2 "IP:        ") $(msg -ama "$(fun_ip)")"
    echo -e " $(msg -verm2 "User:      ") $(msg -ama "$name")"
    echo -e " $(msg -verm2 "Password:  ") $(msg -ama "$pass")"
    echo -e " $(msg -verm2 "Duration:  ") $(msg -ama "$tmp minutes")"
    msg -bar
    menu_func "APPLY DEFAULT CONF" "CUSTOM CONF"
    back
    opcion=$(selection_fun 2)
    case $opcion in
        1)mktmpuser "def";;
        2)unset name
          unset pass
          unset tmp
          mktmpuser;;
        0)return;;
    esac
}
#===========================================

#=====REMOVE USER=======================
rm_user(){
  #name
  if userdel --force "$1" ; then
    sed -i "/$1/d" ${ADM_user}/passwd
      print_center -verd "[$(fun_trans "Removed")]"
  else
      print_center -verm "[$(fun_trans "Not Removed")]"
  fi
}

remove_user(){
    clear
    usuarios_ativos=('' $(mostrar_usuarios))
  msg -bar
    print_center -ama "$(fun_trans "REMOVE USERS")"
    msg -bar
    data_user
    back

    print_center -ama "$(fun_trans "Type or Select a Client")"
    msg -bar
    unset selection
    while [[ -z ${selection} ]]; do
        msg -nazu "$(fun_trans "Select an Option"): " && read selection
        tput cuu1 && tput dl1
    done
    [[ ${selection} = "0" ]] && return

  client_chek=$(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w 'token')

    if [[ ! $(echo "${selection}" | egrep '[^0-9]') ]]; then
        usuario_del="${usuarios_ativos[$selection]}"
    else
    usuario_del=$(echo "$client_chek"|grep -w "$selection"|awk -F ':' '{print $1}')
    fi
    [[ -z $usuario_del ]] && {
        msg -verm "$(fun_trans "Error, Invalid Client")"
        msg -bar
        return 1
    }
    [[ ! $(echo ${usuarios_ativos[@]}|grep -w "$usuario_del") ]] && {
        msg -verm "$(fun_trans "Error, Invalid Client")"
        msg -bar
        return 1
    }

    client=$(echo "$client_chek"|grep -w "$usuario_del"|awk -F ':' '{print $5}'|cut -d ',' -f2)

  print_center -ama "$(fun_trans "Selected Client"): $client"
    pkill -u $usuario_del
    droplim=`droppids|grep -w "$usuario_del"|awk '{print $2}'` 
    kill -9 $droplim &>/dev/null
    rm_user "$usuario_del"
    msg -bar
    sleep 3
}

#========RENEW USERS==========

renew_user_fun(){
  #name days
  datexp=$(date "+%F" -d " + $2 days") && valid=$(date '+%C%y-%m-%d' -d " + $2 days")
  if chage -E $valid $1 ; then
    print_center -ama "$(fun_trans "Client renewed successfully")"
  else
    print_center -verm "$(fun_trans "Error, Client not renewed")"
  fi
}

renew_user(){
  clear
  usuarios_ativos=('' $(mostrar_usuarios))
  msg -bar
  print_center -ama "$(fun_trans "RENEW CLIENT")"
  msg -bar
  data_user
  back

  print_center -ama "$(fun_trans "Type or select a client")"
  msg -bar
  unset selection
  while [[ -z ${selection} ]]; do
    msg -nazu "$(fun_trans " Select an Option"): " && read selection
    tput cuu1 && tput dl1
  done

  [[ ${selection} = "0" ]] && return

  client_chek=$(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w 'token')

  if [[ ! $(echo "${selection}" | egrep '[^0-9]') ]]; then
    useredit="${usuarios_ativos[$selection]}"
  else
    useredit=$(echo "$client_chek"|grep -w "$selection"|awk -F ':' '{print $1}')
  fi

  [[ -z $useredit ]] && {
    msg -verm "$(fun_trans "Error, Invalid Client")"
    msg -bar
    sleep 3
    return 1
  }

  [[ ! $(echo ${usuarios_ativos[@]}|grep -w "$useredit") ]] && {
    msg -verm "$(fun_trans "Error, Invalid Client")"
    msg -bar
    sleep 3
    return 1
  }

  client=$(echo "$client_chek"|grep -w "$useredit"|awk -F ':' '{print $5}'|cut -d ',' -f2)

  while true; do
    msg -ne "$(fun_trans "New Duration for"): $client"
    read -p ": " diasuser
    if [[ -z "$diasuser" ]]; then
      echo -e '\n\n\n'
      err_fun 7 && continue
    elif [[ "$diasuser" != +([0-9]) ]]; then
      echo -e '\n\n\n'
      err_fun 8 && continue
    elif [[ "$diasuser" -gt "360" ]]; then
      echo -e '\n\n\n'
      err_fun 9 && continue
    fi
    break
  done
  msg -bar
  renew_user_fun "${useredit}" "${diasuser}"
  msg -bar
  sleep 3
}

eliminar_all(){
  title "REMOVE ALL CLIENTS"
  msg -ne " [Y/N]: "
  read opcion
  [[ "${opcion}" != @(S|s|y|Y) ]] && return 1
  enter
  service dropbear stop &>/dev/null
  service sshd stop &>/dev/null
  service ssh stop &>/dev/null
  service stunnel4 stop &>/dev/null
  service squid stop &>/dev/null

  cat_users=$(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w "token")

  for user in `echo "$cat_users"|awk -F ':' '{print $1}'`; do
    userpid=$(ps -u $user |awk {'print $1'})
    kill "$userpid" 2>/dev/null
    client=$(echo "$cat_users"|grep -w "$user"|awk -F ':' '{print $5}'|cut -d ',' -f2)
    userdel --force $user
    user2=$(printf '%-15s' "$client")
    echo -e " $(msg -azu "CLIENT:") $(msg -ama "$user2")$(msg -verm2 "Removed")"
  done
  service sshd restart &>/dev/null
  service ssh restart &>/dev/null
  service dropbear start &>/dev/null
  service stunnel4 start &>/dev/null
  service squid restart &>/dev/null
  msg -bar
  print_center -ama "CONNECTIONS REMOVED"
  enter
  return 1
}

sshmonitor(){
  clear
  cat_users=$(cat "/etc/passwd"|grep 'home'|grep 'false'|grep -v 'syslog')
  cab=$(printf '%-15s%-13s%-15s%-9s' 'USER' 'STATUS' 'CONNECTIONS' 'TIME')
  msg -bar 
  echo -e "\E[41;1;37m $cab\E[0m"
  msg -bar
    for i in `echo "$cat_users"|awk -F ':' '{print $1}'`; do
        user="$i"
        s2ssh="$(echo "$cat_users"|grep -w "$i"|awk -F ':' '{print $5}'|cut -d ',' -f1)"

        if [[ "$(echo "$cat_users"| grep -w $i| wc -l)" = "1" ]]; then
          sqd="$(ps -u $user | grep sshd | wc -l)"
        else
          sqd=00
        fi

        [[ "$sqd" = "" ]] && sqd=0
        if [[ -e /etc/openvpn/openvpn-status.log ]]; then
          ovp="$(cat /etc/openvpn/openvpn-status.log | grep -E ,"$i", | wc -l)"
        else
          ovp=0
        fi

        if netstat -nltp|grep 'dropbear'> /dev/null;then
          drop="$(droppids | grep "$i" | wc -l)"
        else
          drop=0
        fi
        
        cnx=$(($sqd + $drop))
        conex=$(($cnx + $ovp))
        if [[ $cnx -gt 0 ]]; then
          tst="$(ps -o etime $(ps -u $i |grep sshd |awk 'NR==1 {print $1}')|awk 'NR==2 {print $1}')"
          tst1=$(echo "$tst" | wc -c)
        if [[ "$tst1" == "9" ]]; then 
          timerr="$(ps -o etime $(ps -u $i |grep sshd |awk 'NR==1 {print $1}')|awk 'NR==2 {print $1}')"
        else
          timerr="$(echo "00:$tst")"
        fi
        elif [[ $ovp -gt 0 ]]; then
          tmp2=$(printf '%(%H:%M:%S)T\n')
          tmp1="$(grep -w "$i" /etc/openvpn/openvpn-status.log |awk '{print $4}'| head -1)"
          [[ "$tmp1" = "" ]] && tmp1="00:00:00" && tmp2="00:00:00"
          var1=`echo $tmp1 | cut -c 1-2`
          var2=`echo $tmp1 | cut -c 4-5`
          var3=`echo $tmp1 | cut -c 7-8`
          var4=`echo $tmp2 | cut -c 1-2`
          var5=`echo $tmp2 | cut -c 4-5`
          var6=`echo $tmp2 | cut -c 7-8`
          calc1=`echo $var1*3600 + $var2*60 + $var3 | bc`
          calc2=`echo $var4*3600 + $var5*60 + $var6 | bc`
          seg=$(($calc2 - $calc1))
          min=$(($seg/60))
          seg=$(($seg-$min*60))
          hor=$(($min/60))
          min=$(($min-$hor*60))
          timerusr=`printf "%02d:%02d:%02d \n" $hor $min $seg;`
          timerr=$(echo "$timerusr" | sed -e 's/[^0-9:]//ig' )
        else
          timerr="00:00:00"
        fi

        if [[ "$s2ssh" != @(hwid|token) ]]; then
          user=$(printf '%-15s' "$i")
          con=$(printf '%-11s' "$conex/$s2ssh")
        else
          fix="$(echo "$cat_users"|grep -w "$i"|awk -F ':' '{print $5}'|cut -d ',' -f2)"
          user=$(printf '%-15s' "$fix")
          con=$(printf '%-11s' "$(echo $s2ssh|awk '{print toupper($0)}')")
        fi

        if [[ $conex -eq 0 ]]; then
           status=$(printf '%-16s' 'Offline')
           echo -e " $(msg -ama "$user")$(msg -verm2 "$status")$(msg -verd "$con")$(msg -ama "$timerr")"
        else
           status=$(printf '%-16s' 'Online')
           echo -e " $(msg -ama "$user")$(msg -verd "$status")$(msg -verd "$con")$(msg -ama "$timerr")"
        fi
        msg -bar3
      done
    tput cuu1 && tput dl1
    msg -bar
    print_center -ama "►► Press enter to continue ◄◄"
    read
}

detail_user(){
    clear
    usuarios_ativos=('' $(mostrar_usuarios))
    if [[ -z ${usuarios_ativos[@]} ]]; then
        msg -bar
        print_center -verm2 "$(fun_trans "No registered clients")"
        msg -bar
        sleep 3
        return
    else
        msg -bar
        print_center -ama "$(fun_trans "CLIENT DETAILS")"
        msg -bar
    fi
    data_user
    enter
}

block_user(){
  clear
  usuarios_ativos=('' $(mostrar_usuarios))
  msg -bar
    print_center -ama "$(fun_trans "BLOCK/UNBLOCK CLIENT")"
    msg -bar
  data_user
  back

  print_center -ama "$(fun_trans "Type or Select a Client")"
  msg -bar
  unset selection
  while [[ ${selection} = "" ]]; do
    echo -ne "\033[1;37m Select: " && read selection
    tput cuu1 && tput dl1
  done
  [[ ${selection} = "0" ]] && return

  client_chek=$(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w 'token')

  if [[ ! $(echo "${selection}" | egrep '[^0-9]') ]]; then
    usuario_del="${usuarios_ativos[$selection]}"
  else
    usuario_del=$(echo "$client_chek"|grep -w "$selection"|awk -F ':' '{print $1}')
  fi
  [[ -z $usuario_del ]] && {
    msg -verm "$(fun_trans "Error, Invalid Client")"
    msg -bar
    return 1
  }
  [[ ! $(echo ${usuarios_ativos[@]}|grep -w "$usuario_del") ]] && {
    msg -verm "$(fun_trans "Error, Invalid Client")"
    msg -bar
    return 1
  }

  client=$(echo "$client_chek"|grep -w "$usuario_del"|awk -F ':' '{print $5}'|cut -d ',' -f2)

  msg -nama "   $(fun_trans "Client"): $client >>>> "

  if [[ $(passwd --status $usuario_del|cut -d ' ' -f2) = "P" ]]; then
    pkill -u $usuario_del &>/dev/null
    droplim=`droppids|grep -w "$usuario_del"|awk '{print $2}'` 
    kill -9 $droplim &>/dev/null
    usermod -L $usuario_del &>/dev/null
    sleep 2
    msg -verm2 "$(fun_trans "Blocked")"
  else
      usermod -U $usuario_del
      sleep 2
      msg -verd "$(fun_trans "Unblocked")"
  fi
  enter
}

rm_vencidos(){
    title "REMOVE EXPIRED CLIENTS"
    print_center -ama " Will remove all expired token clients"
    msg -bar
    msg -ne " Continue [Y/N]: "
    read opcion
    tput cuu1 && tput dl1
    [[ "$opcion" != @(s|S|y|Y) ]] && return

    expired="$(fun_trans "Expired")"
    removido="$(fun_trans "Removed")"
    DataVPS=$(date +%s)

    while read user; do
        DataUser=$(chage -l "$user"|sed -n '4p'|awk -F ': ' '{print $2}')
        [[ "$DataUser" = @(never|nunca) ]] && continue
        #[[ "$DataUser" = "ene 01, 1970" ]] && DataUser="Jan 01, 1970"
        DataSEC=$(date +%s --date="$DataUser")

        if [[ "$DataSEC" -lt "$DataVPS" ]]; then
            pkill -u $user
            droplim=`droppids|grep -w "$user"|awk '{print $2}'` 
            kill -9 $droplim &>/dev/null
      client=$(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w 'token'|grep -w "$user"|awk -F ':' '{print $5}'|cut -d ',' -f2)
            userdel $user
            print_center -ama "$client $expired ($removido)"
            sleep 1
        fi
    done <<< "$(mostrar_usuarios)"
    enter
}

limiter(){

    ltr(){
        clear
        msg -bar
    l_cron=$(cat /var/spool/cron/crontabs/root|grep -w 'limitador.sh'|grep -w 'token')
    if [[ -z "$l_cron" ]]; then
      echo '@daily /etc/ADMRufu/install/limitador.sh --token' >> /var/spool/cron/crontabs/root
      print_center -verd "Expired limiter scheduled\nit will run daily at 00:00 according to server time"
      enter
      return
    else
      sed -i '/limitador.sh --token/d' /var/spool/cron/crontabs/root
      print_center -verm2 "Expired limiter stopped"
      enter
      return   
    fi
    }

    log(){
        clear
        msg -bar
        print_center -ama "LIMITER LOG"
        msg -bar
        [[ ! -e ${ADM_user}/limit.log ]] && touch ${ADM_user}/limit.log
        if [[ -z $(cat ${ADM_user}/limit.log) ]]; then
            print_center -ama "no limiter log found"
            msg -bar
            sleep 2
            return
        fi
        msg -teal "$(cat ${ADM_user}/limit.log)"
        msg -bar
        print_center -ama "►► Press enter to continue or ◄◄"
        print_center -ama "►► 0 to clear log ◄◄"
        read opcion
        [[ $opcion = "0" ]] && echo "" > ${ADM_user}/limit.log
    }

    clear
    msg -bar
    print_center -ama "ACCOUNT LIMITER"
    msg -bar
    menu_func "EXPIRED LIMITER" "DATA LIMITER $(msg -verm2 "(not available)")" "LIMITER LOG"
    back
    msg -ne " option: "
    read opcion
    case $opcion in
        1)ltr;;
        2);;
        3)log;;
        0)return;;
    esac
}

USER_MODE(){
  title "SELECT DEFAULT MODE TO USE"
  menu_func "SSH" "HWID"
  back
  opcion=$(selection_fun 2)
  case $opcion in
    1) echo "userSSH" > ${ADM_user}/userMODE
       clear
       msg -bar
       print_center -verd "SSH MODE ACTIVE"
       enter;;
    2) echo "userHWID" > ${ADM_user}/userMODE
       clear
       msg -bar
       print_center -verd "HWID MODE ACTIVE"
       enter;;
    0)return 1;;
  esac
}

tpass(){
  fpass="${ADM_user}/passwd_token" && [[ ! -e "${fpass}" ]] && touch ${fpass}
  apass=$(cat ${ADM_user}/passwd_token)
  title -ama "TOKEN PASSWORD CONFIG"
  if [[ ! -z "$apass" ]]; then
    print_center -azu "CURRENT PASSWORD: $apass"
    msg -bar
  fi
  while true; do
    echo -e " $(msg -verm3 "╭╼╼╼[")$(msg -azu "ENTER YOUR PASSWORD, ENTER TO CANCEL")$(msg -verm3 "]")"
    echo -ne " $(msg -verm3 "╰╼")\033[37;1m> " && read npass
    npass="$(echo $npass|sed 'y/áÁàÀãÃâÂéÉêÊíÍóÓõÕôÔúÚñÑçÇªº/aAaAaAaAeEeEiIoOoOoOuUnNcCao/')"
    if [[ -z $npass ]]; then
      break
    elif [[ "${#npass}" -lt "6" ]]; then
      err_fun 5 && tput cuu1 && tput dl1 && continue
    elif [[ "${#npass}" -gt "32" ]]; then
      err_fun 6 && tput cuu1 && tput dl1 && continue
    fi
    break
  done
  [[ -z "$npass" ]] && return 1
  tput cuu1 && tput dl1 && tput cuu1 && tput dl1
  printf "$npass" > ${ADM_user}/passwd_token
  clear
  msg -bar
  echo -e " $(msg -verd "╭╼╼╼╼╼╼╼╼╼[")$(msg -azu "NEW PASSWORD SAVED")$(msg -verd "]")"
  echo -ne " $(msg -verd "╰╼")\033[37;1m> " && msg -azu "$npass"
  cat_users=$(cat "/etc/passwd"|grep 'home'|grep 'false'|grep -v 'syslog'|grep -w 'token'|awk -F ':' '{print $1}')
  [[ ! -z "$cat_users" ]] && msg -bar && msg -nama " APPLY TO ALL CLIENTS [Y/N]: " && read allpass
  if [[ "$allpass" = @(S|s) ]]; then
    msg -bar
    print_center -ama "PASSWORD APPLIED TO ALL CLIENTS"
    for u in `echo "$cat_users"`; do
      (echo $npass; echo $npass)|passwd $u 2>/dev/null
    done
    tput cuu1 && tput dl1
    print_center -verd "PASSWORD APPLIED TO ALL CLIENTS"
  fi
  enter
  return 1
}

while :
do

  [[ $(cat /var/spool/cron/crontabs/root|grep -w 'limitador.sh'|grep -w 'token') ]] && lim=$(msg -verd "[ON]") || lim=$(msg -verm2 "[OFF]")

    title -ama "TOKEN USER MANAGEMENT"

    menu_func "NEW TOKEN CLIENT ✏️ " \
"$(msg -verm2 "REMOVE CLIENT") 🗑 " \
"$(msg -verd "EDIT/RENEW CLIENT") ♻️" \
"-bar3 BLOCK/UNBLOCK CLIENT 🔒" \
"-bar3 CONFIGURE TOKEN PASSWORD" \
"$(msg -verd "DETAILS OF ALL CLIENTS") 🔎" \
"CONNECTED CLIENTS MONITOR" \
"-bar3 🔒 $(msg -ama "ACCOUNT-LIMITER-EXPIRED") 🔒 $lim" \
"REMOVE EXPIRED CLIENTS" \
"-bar3 ⚠️ $(msg -verm2 "REMOVE ALL CLIENTS") ⚠️" \
"CLIENTS BACKUP" \
"-bar DISABLE ALPHANUMERIC PASS $(msg -blu "(VULTR)")" \
"SWITCH TO SSH/HWID MODE"

    back
    selection=$(selection_fun 13)
    case ${selection} in
        0)break;;
        1)new_user;;
        2)remove_user;;
        3)renew_user;;
        4)block_user;;
    5)tpass;;
        6)detail_user;;
        7)sshmonitor;;
        8)limiter;;
        9)rm_vencidos;;
        10)eliminar_all;;
        11)backup;;
        12)ULK_ALF;;
    13)USER_MODE && break;;
    esac
done