#!/bin/bash

# Color interface
msg(){
  COLOR[0]='\033[1;37m' #WHITE='\033[1;37m'
  COLOR[1]='\e[31m' #RED='\e[31m'
  COLOR[2]='\e[32m' #GREEN='\e[32m'
  COLOR[3]='\e[33m' #YELLOW='\e[33m'
  COLOR[4]='\e[34m' #BLUE='\e[34m'
  COLOR[5]='\e[91m' #MAGENTA='\e[35m'
  COLOR[6]='\033[1;97m' #CYAN='\033[1;36m'
  COLOR[7]='\e[36m' #teal='\e[36m'
  COLOR[8]='\e[30m' #black='\e[30m'
  COLOR[9]='\033[34m' #blue='\033[1;34m'

  BOLD='\e[1m'
  RESET='\e[0m'

  case $1 in
    -ne)   cor="${COLOR[1]}${BOLD}" && echo -ne "${cor}${2}${RESET}";;
    -nazu) cor="${COLOR[6]}${BOLD}" && echo -ne "${cor}${2}${RESET}";;
    -nverd)cor="${COLOR[2]}${BOLD}" && echo -ne "${cor}${2}${RESET}";;
    -nama) cor="${COLOR[3]}${BOLD}" && echo -ne "${cor}${2}${RESET}";;
    -ama)  cor="${COLOR[3]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -verm) cor="${COLOR[3]}${BOLD}[!] ${COLOR[1]}" && echo -e "${cor}${2}${RESET}";;
    -verm2)cor="${COLOR[1]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -verm3)cor="${COLOR[1]}" && echo -e "${cor}${2}${RESET}";;
    -teal) cor="${COLOR[7]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -teal2)cor="${COLOR[7]}" && echo -e "${cor}${2}${RESET}";;
    -blak) cor="${COLOR[8]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -blak2)cor="${COLOR[8]}" && echo -e "${cor}${2}${RESET}";;
    -azu)  cor="${COLOR[6]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -blu)  cor="${COLOR[9]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -blu1) cor="${COLOR[9]}" && echo -e "${cor}${2}${RESET}";;
    -verd) cor="${COLOR[2]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -bra)  cor="${COLOR[0]}${BOLD}" && echo -e "${cor}${2}${RESET}";;
    -bar)  cor="${COLOR[1]}=====================================================" && echo -e "${RESET}${cor}${RESET}";;
    -bar2) cor="${COLOR[7]}=====================================================" && echo -e "${RESET}${cor}${RESET}";;
    -bar3) cor="${COLOR[1]}-----------------------------------------------------" && echo -e "${RESET}${cor}${RESET}";;
    -bar4) cor="${COLOR[7]}-----------------------------------------------------" && echo -e "${RESET}${cor}${RESET}";;
  esac
}

# Center text
print_center(){
  if [[ -z $2 ]]; then
    text="$1"
  else
    col="$1"
    text="$2"
  fi

  while read line; do
    unset space
    x=$(( ( 54 - ${#line}) / 2))
    for (( i = 0; i < $x; i++ )); do
      space+=' '
    done
    space+="$line"
    if [[ -z $2 ]]; then
      msg -azu "$space"
    else
      msg "$col" "$space"
    fi
  done <<< $(echo -e "$text")
}

# Titles and headers
title(){
    clear
    msg -bar
    if [[ -z $2 ]]; then
      print_center -azu "$1"
    else
      print_center "$1" "$2"
    fi
    msg -bar
}

# Task completion
enter(){
  msg -bar
  text="►► Press enter to continue ◄◄"
  if [[ -z $1 ]]; then
    print_center -ama "$text"
  else
    print_center "$1" "$text"
  fi
  read
}

# Back/Return option
back(){
    msg -bar
    echo -ne "$(msg -verd " [0]") $(msg -verm2 ">") " && msg -bra "\033[1;41mRETURN"
    msg -bar
}

# Menu maker (options 1, 2, 3,.....)
menu_func(){
  local options=${#@}
  local array
  for((num=1; num<=$options; num++)); do
    echo -ne "$(msg -verd " [$num]") $(msg -verm2 ">") "
    array=(${!num})
    case ${array[0]} in
      "-vd")echo -e "\033[1;33m[!]\033[1;32m ${array[@]:1}";;
      "-vm")echo -e "\033[1;33m[!]\033[1;31m ${array[@]:1}";;
      "-fi")echo -e "${array[@]:2} ${array[1]}";;
      -bar|-bar2|-bar3|-bar4)echo -e "\033[1;37m${array[@]:1}\n$(msg ${array[0]})";;
      *)echo -e "\033[1;37m${array[@]}";;
    esac
  done
}

# Numeric selection option
selection_fun(){
  local selection="null"
  local range
  if [[ -z $2 ]]; then
    opcion=$1
    col="-nazu"
  else
    opcion=$2
    col=$1
  fi
  for((i=0; i<=$opcion; i++)); do range[$i]="$i "; done
  while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
    msg "$col" " Select an Option: " >&2
    read selection
    tput cuu1 >&2 && tput dl1 >&2
  done
  echo $selection
}

in_opcion(){
  unset opcion
  if [[ -z $2 ]]; then
      msg -nazu " $1: " >&2
  else
      msg $1 " $2: " >&2
  fi
  read opcion
  echo "$opcion"
}

in_opcion_down(){
  dat=$1
  length=${#dat}
  cal=$(( 22 - $length / 2 ))
  line=''
  for (( i = 0; i < $cal; i++ )); do
    line+='╼'
  done
  echo -e " $(msg -verm3 "╭$line╼[")$(msg -azu "$dat")$(msg -verm3 "]")"
  echo -ne " $(msg -verm3 "╰╼")\033[37;1m> " && read opcion
}

export -f msg
export -f selection_fun
export -f menu_func
export -f print_center
export -f title
export -f back
export -f enter
export -f in_opcion
export -f in_opcion_down